const poster_block = document.getElementById('poster_block')
const poster_block_banner = document.getElementById('poster_block_banner')
const poster_block_banner_text = document.getElementById('poster_block_banner_text')
const poster_block_scroller = document.getElementById('poster_block_scroller')
const poster_block_scroller_sqr = document.getElementById('poster_block_scroller_sqr')

const poster_block_scroller_sqr_block_0 = document.getElementById('poster_block_scroller_sqr_block_0')
const poster_block_scroller_sqr_block_1 = document.getElementById('poster_block_scroller_sqr_block_1')
const poster_block_scroller_sqr_block_2 = document.getElementById('poster_block_scroller_sqr_block_2')
const poster_block_scroller_sqr_block_3 = document.getElementById('poster_block_scroller_sqr_block_3')
const poster_block_scroller_sqr_block_4 = document.getElementById('poster_block_scroller_sqr_block_4')
const poster_block_scroller_sqr_block_5 = document.getElementById('poster_block_scroller_sqr_block_5')
const poster_block_scroller_sqr_block_6 = document.getElementById('poster_block_scroller_sqr_block_6')
const poster_block_scroller_sqr_block_7 = document.getElementById('poster_block_scroller_sqr_block_7')
const poster_block_scroller_sqr_block_8 = document.getElementById('poster_block_scroller_sqr_block_8')
const poster_block_scroller_sqr_block_9 = document.getElementById('poster_block_scroller_sqr_block_9')
const poster_block_scroller_sqr_block_10 = document.getElementById('poster_block_scroller_sqr_block_10')
const poster_block_scroller_sqr_block_11 = document.getElementById('poster_block_scroller_sqr_block_11')
const poster_block_scroller_sqr_block_12 = document.getElementById('poster_block_scroller_sqr_block_12')
const poster_block_scroller_sqr_block_13 = document.getElementById('poster_block_scroller_sqr_block_13')
const poster_block_scroller_sqr_block_14 = document.getElementById('poster_block_scroller_sqr_block_14')
const poster_block_scroller_sqr_block_15 = document.getElementById('poster_block_scroller_sqr_block_15')
const poster_block_scroller_sqr_block_16 = document.getElementById('poster_block_scroller_sqr_block_16')
const poster_block_scroller_sqr_block_17 = document.getElementById('poster_block_scroller_sqr_block_17')
const poster_block_scroller_sqr_block_18 = document.getElementById('poster_block_scroller_sqr_block_18')
const poster_block_scroller_sqr_block_19 = document.getElementById('poster_block_scroller_sqr_block_19')

const poster_block_scroller_sqr_block_0_text = document.getElementById('poster_block_scroller_sqr_block_0_text')
const poster_block_scroller_sqr_block_1_text = document.getElementById('poster_block_scroller_sqr_block_1_text')
const poster_block_scroller_sqr_block_2_text = document.getElementById('poster_block_scroller_sqr_block_2_text')
const poster_block_scroller_sqr_block_3_text = document.getElementById('poster_block_scroller_sqr_block_3_text')
const poster_block_scroller_sqr_block_4_text = document.getElementById('poster_block_scroller_sqr_block_4_text')
const poster_block_scroller_sqr_block_5_text = document.getElementById('poster_block_scroller_sqr_block_5_text')
const poster_block_scroller_sqr_block_6_text = document.getElementById('poster_block_scroller_sqr_block_6_text')
const poster_block_scroller_sqr_block_7_text = document.getElementById('poster_block_scroller_sqr_block_7_text')
const poster_block_scroller_sqr_block_8_text = document.getElementById('poster_block_scroller_sqr_block_8_text')
const poster_block_scroller_sqr_block_9_text = document.getElementById('poster_block_scroller_sqr_block_9_text')
const poster_block_scroller_sqr_block_10_text = document.getElementById('poster_block_scroller_sqr_block_10_text')
const poster_block_scroller_sqr_block_11_text = document.getElementById('poster_block_scroller_sqr_block_11_text')
const poster_block_scroller_sqr_block_12_text = document.getElementById('poster_block_scroller_sqr_block_12_text')
const poster_block_scroller_sqr_block_13_text = document.getElementById('poster_block_scroller_sqr_block_13_text')
const poster_block_scroller_sqr_block_14_text = document.getElementById('poster_block_scroller_sqr_block_14_text')
const poster_block_scroller_sqr_block_15_text = document.getElementById('poster_block_scroller_sqr_block_15_text')
const poster_block_scroller_sqr_block_16_text = document.getElementById('poster_block_scroller_sqr_block_16_text')
const poster_block_scroller_sqr_block_17_text = document.getElementById('poster_block_scroller_sqr_block_17_text')
const poster_block_scroller_sqr_block_18_text = document.getElementById('poster_block_scroller_sqr_block_18_text')
const poster_block_scroller_sqr_block_19_text = document.getElementById('poster_block_scroller_sqr_block_19_text')


poster_block.style.width = `${prcnt_windowInnerWidth *95.8}px`
poster_block_banner.style.width = `${windowInnerWidth}px`
if(aspect_ratio < 1.34){
    poster_block_scroller.style.width = `${prcnt_windowInnerWidth * 95.8-8}px`
    poster_block_scroller_sqr.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_0.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_1.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_2.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_3.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_4.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_5.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_6.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_7.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_8.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_9.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_10.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_11.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_12.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_13.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_14.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_15.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_16.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_17.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_18.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_19.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`

    poster_block_scroller_sqr_block_0_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_1_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_2_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_3_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_4_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_5_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_6_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_7_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_8_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_9_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_10_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_11_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_12_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_13_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_14_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_15_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_16_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_17_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_18_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
    poster_block_scroller_sqr_block_19_text.style.width = `${prcnt_windowInnerWidth * 95.8-8 -49}px`
}
if(aspect_ratio > 1.34){
    poster_block_scroller.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8}px`
    poster_block_scroller_sqr.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8-49}px`
    
    poster_block_scroller_sqr_block_0.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_1.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_2.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_3.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_4.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_5.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_6.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_7.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_8.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_9.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_10.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_11.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_12.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_13.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_14.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_15.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_16.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_17.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_18.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_19.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`

    poster_block_scroller_sqr_block_0_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_1_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_2_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_3_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_4_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_5_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_6_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_7_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_8_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_9_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_10_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_11_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_12_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_13_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_14_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_15_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_16_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_17_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_18_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
    poster_block_scroller_sqr_block_19_text.style.width = `${((prcnt_windowInnerWidth * 95.8)*9/10)-8 -49}px`
}
poster_block_scroller.style.left = `${(windowInnerWidth -(prcnt_windowInnerWidth * 95.8))/2}px`
poster_block_banner_text.style.left = `${(windowInnerWidth-333)/2}px`
// poster_block
